version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts-stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set Up Environment
          command: |
            mkdir ci_scripts
            curl -H "Authorization: token $GITHUB_TOKEN" -H "Accept:application/vnd.github.v3.raw" https://api.github.com/repos/6RiverSystems/ci_scripts/contents/ci_tool.sh > ci_scripts/ci_tool.sh
            chmod +x ci_scripts/ci_tool.sh
            ci_scripts/ci_tool.sh --setup_npm
      - run:
          name: Initalize Docker
          command: |
            ci_scripts/ci_tool.sh --docker_login
      - run:
          name: Build image
          command: |
            docker build --pull --no-cache -t gcr.io/plasma-column-128721/pubsub-emulator:latest .
      - run:
          name: Push image if master
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              docker push gcr.io/plasma-column-128721/pubsub-emulator:latest
            fi
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: 6rs-circle
  # don't auto-build this any more, we don't use it any more
  # nightly:
  #   triggers:
  #     - schedule:
  #         # this doesn't update often, run weekly in the wee hours of Monday morning
  #         cron: "0 1 * * 1"
  #         filters:
  #           branches:
  #             only:
  #               - master
  #   jobs:
  #     - build:
  #         context: 6rs-circle
